#!/usr/bin/env python3
"""Markdown renderer for the unified index model.

Serializes the model as a **navigational index** (key → file location), never the
files' content. When the model is partitioned by domain it writes an `INDEX.md`
overview plus one `<domain>.md` per domain; otherwise it writes a single
`INDEX.md` holding the views directly. Each file is led by a file-type-agnostic
how-to header. Every non-empty, non-suppressed view is serialized as nested-list
mappings whose leaves are markdown links to the indexed files.

See docs/DESIGN_PRINCIPLES_AND_DECISIONS.md (D16) and docs/REFERENCE.md.
"""

import os
import re
from pathlib import Path
from typing import Dict, List, Any, Optional

from index_model import (marker_comment, view_enabled, VIEW_FILE_SYSTEM,
                         VIEW_KEYWORD, VIEW_TAG, VIEW_WORD, VIEW_DEPENDENCIES,
                         VIEW_GLOSSARY)

RENDERER = "markdown"


class MarkdownIndexRenderer:
    """Render the index model to a directory of markdown index files."""

    def __init__(self, config: Dict[str, Any]):
        self.config = config

    # -- entry point ---------------------------------------------------------

    def render_model(self, model) -> str:
        out = Path(self.config["output"]["file"])
        out.mkdir(parents=True, exist_ok=True)
        written: List[str] = []

        if model.partitioned:
            overview = [self._header("Catalog"), "## Domains", ""]
            for name, di in model.ordered_domains():
                fname = f"{self._slugify(name)}.md"
                overview.append(f"- [{name}]({fname}) — {len(di.files)} file(s)")
                (out / fname).write_text(self._render_domain(name, di), encoding="utf-8")
                written.append(str(out / fname))
            (out / "INDEX.md").write_text("\n".join(overview).rstrip() + "\n", encoding="utf-8")
            written.append(str(out / "INDEX.md"))
        else:
            di = model.domains.get(None)
            body = self._header("Index") + (self._render_views(di) if di else "")
            (out / "INDEX.md").write_text(body.rstrip() + "\n", encoding="utf-8")
            written.append(str(out / "INDEX.md"))

        return str(out)

    # -- file assembly -------------------------------------------------------

    def _render_domain(self, name: str, di) -> str:
        return (self._header(name) + self._render_views(di)).rstrip() + "\n"

    def _render_views(self, di) -> str:
        parts: List[str] = []
        has_fs = di.file_system or di.card_groups
        if has_fs and view_enabled(self.config, VIEW_FILE_SYSTEM, RENDERER):
            parts.append(self._render_file_system(di.file_system, di.card_groups))
        if di.keyword_entries and view_enabled(self.config, VIEW_KEYWORD, RENDERER):
            parts.append(self._render_keyword(di.keyword_entries))
        if di.tags and view_enabled(self.config, VIEW_TAG, RENDERER):
            parts.append(self._render_tags(di.tags))
        if di.words and view_enabled(self.config, VIEW_WORD, RENDERER):
            parts.append(self._render_words(di.words))
        if di.dependencies and view_enabled(self.config, VIEW_DEPENDENCIES, RENDERER):
            parts.append(self._render_dependencies(di.dependencies))
        if di.glossary and view_enabled(self.config, VIEW_GLOSSARY, RENDERER):
            parts.append(self._render_glossary(di.glossary))
        return "\n".join(parts)

    # -- helpers -------------------------------------------------------------

    @staticmethod
    def _slugify(name: str) -> str:
        return re.sub(r"[^a-z0-9._-]+", "-", str(name).lower()).strip("-") or "index"

    @staticmethod
    def _link(label: str, target: str) -> str:
        # angle brackets allow spaces in the path
        return f"[{label}](<{target}>)"

    @staticmethod
    def _label(file_path: str, root_nodes) -> str:
        """Card → its title (the H1); other files → the filename."""
        if file_path.endswith(".kb.md") and root_nodes:
            text = getattr(root_nodes[0], "text", None)
            if text:
                return text
        return Path(file_path).name

    def _header(self, title: str) -> str:
        return (
            f"{marker_comment()}\n\n"
            f"# Knowledge Base Index — {title}\n\n"
            "> Navigational index built by `kbi` — it maps keys to **file "
            "locations**, not content. Each entry links to an indexed file; open "
            "the linked file to read it. Use the sections below to find relevant "
            "files, then open them. Do not edit (regenerated by `kbi`).\n\n"
        )

    # -- views ---------------------------------------------------------------

    def _render_file_system(self, file_system: Dict[str, list], card_groups=None) -> str:
        """Render the File System view.

        Non-card files appear as leaf links (unchanged). Cards are grouped under
        their source path: the source node is annotated with an essence line
        when available (from a `kind: file_summary` card or a lone topic card),
        and each topic card appears as a child leaf under the source node (D21).
        """
        if card_groups is None:
            card_groups = {}

        all_paths = list(file_system.keys()) + list(card_groups.keys())
        if not all_paths:
            return ""
        dirs = [os.path.dirname(p) for p in all_paths]
        base = os.path.commonpath(dirs) if len(set(dirs)) > 1 else dirs[0]

        tree: Dict[str, Any] = {}

        def insert(path, **kwargs):
            rel = os.path.relpath(path, base)
            parts = rel.split(os.sep)
            node = tree
            for p in parts[:-1]:
                node = node.setdefault(p, {})
            bucket = node.setdefault("__entries__", [])
            bucket.append({"path": path, "name": parts[-1], **kwargs})

        for f in file_system.keys():
            insert(f, kind="file", root_nodes=file_system[f])
        for source, group in card_groups.items():
            insert(source, kind="card_group", group=group)

        lines = ["## File System", "", f"Base: `{base}`", ""]

        def walk(node, depth):
            entries = sorted(node.get("__entries__", []), key=lambda e: e["name"])
            for e in entries:
                if e["kind"] == "file":
                    label = self._label(e["path"], e["root_nodes"])
                    lines.append("\t" * depth + f"- {self._link(label, e['path'])}")
                else:  # card_group
                    group = e["group"]
                    source_label = Path(e["path"]).name
                    annotation = f" — {group.annotation}" if group.annotation else ""
                    lines.append("\t" * depth + f"- {self._link(source_label, e['path'])}{annotation}")
                    visible = [
                        (lbl, cp) for lbl, cp in group.cards
                        if cp != group.hidden_card
                    ]
                    for lbl, cp in sorted(visible, key=lambda x: x[0].lower()):
                        lines.append("\t" * (depth + 1) + f"- {self._link(lbl, cp)}")
            for d in sorted(k for k in node if k != "__entries__"):
                lines.append("\t" * depth + f"- {d}/")
                walk(node[d], depth + 1)

        walk(tree, 0)
        return "\n".join(lines) + "\n"

    def _render_tags(self, tags: Dict[str, list]) -> str:
        lines = ["## Tags", ""]
        for tag in sorted(tags, key=str.lower):
            lines.append(f"- {tag}")
            seen = set()
            for entry in tags[tag]:
                file_path, _node_id, label = entry
                if file_path in seen:
                    continue
                seen.add(file_path)
                lines.append("\t" + f"- {self._link(label or Path(file_path).name, file_path)}")
        return "\n".join(lines) + "\n"

    def _render_words(self, words: Dict[str, dict]) -> str:
        lines = ["## Word Index", ""]
        for word in sorted(words, key=str.lower):
            lines.append(f"- {word}")
            for file_path in sorted(words[word].keys()):
                lines.append("\t" + f"- {self._link(Path(file_path).name, file_path)}")
        return "\n".join(lines) + "\n"

    def _render_dependencies(self, dependencies) -> str:
        lines = ["## Dependencies", ""]
        for rec, targets in sorted(dependencies, key=lambda d: (d[0].get("title") or "").lower()):
            label = rec.get("title") or Path(rec.get("file_path", "")).name
            lines.append(f"- {self._link(label, rec.get('file_path', ''))}")
            for tlabel, tpath in targets:
                if tpath:
                    lines.append("\t" + f"- builds on: {self._link(tlabel, tpath)}")
                else:
                    lines.append("\t" + f"- builds on: {tlabel}")
        return "\n".join(lines) + "\n"

    def _render_glossary(self, glossary: Dict[str, dict]) -> str:
        lines = ["## Glossary", ""]
        for term in sorted(glossary, key=str.lower):
            rec = glossary[term]
            label = rec.get("title") or Path(rec.get("file_path", "")).name
            lines.append(f"- {term} → {self._link(label, rec.get('file_path', ''))}")
        return "\n".join(lines) + "\n"

    def _render_keyword(self, keyword_entries) -> str:
        """Keyword view: the keyword hierarchy with file links under leaf matches.

        Keyword search results are usually absent for card catalogs (no keyword
        file configured); rendered best-effort when present.
        """
        lines = ["## Keyword Index", ""]

        def files_from_results(results) -> List[str]:
            if isinstance(results, dict):
                return list(results.keys())
            if isinstance(results, (list, tuple)):
                out = []
                for item in results:
                    if isinstance(item, str):
                        out.append(item)
                    elif isinstance(item, dict) and "file_path" in item:
                        out.append(item["file_path"])
                return out
            return []

        def walk(entries, depth):
            for entry in entries:
                text = getattr(entry, "text", str(entry))
                lines.append("\t" * depth + f"- {text}")
                results = getattr(entry, "search_results", None)
                for fp in sorted(set(files_from_results(results))):
                    lines.append("\t" * (depth + 1) + f"- {self._link(Path(fp).name, fp)}")
                children = getattr(entry, "children", None)
                if children:
                    walk(children, depth + 1)

        walk(keyword_entries, 0)
        return "\n".join(lines) + "\n"
